/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs430.finalProject.frontEnd;

import cs430.finalProject.backEnd.FacultyDatabase;
import cs430.finalProject.backEnd.GeneralDatabase;
import cs430.finalProject.backEnd.MainClassHolder;
import cs430.finalProject.backEnd.StudentDatabase;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author kreuter
 */
public class FacultyForm extends javax.swing.JFrame {

    /**
     * Creates the faculty form
     * @param fid Faculty ID that was used to open the form
     */
    public FacultyForm(int fid) {
        facultyDatabase = MainClassHolder.getFacultyDatabase();
        studentDatabase = MainClassHolder.getStudentDatabase();
        generalDatabase = MainClassHolder.getGeneralDatabase();

        majorList = studentDatabase.getMajors();
        levelList = studentDatabase.getLEVELS();
        courseList = generalDatabase.getCourses();
        studentList = studentDatabase.getStudents();

        studentData = studentDatabase.searchStudent();
        courseData = generalDatabase.searchCourse();

        this.fid = fid;

        Object[][] facultyData = facultyDatabase.facultySearch(fid, null, null);
        fName = (String) facultyData[0][1];
        did = (Integer) facultyData[0][2];

        initComponents();
    }

    private void refresh(JTable table, String[] columns, Object[][] data) {
        DefaultTableModel defaultTableModel = new DefaultTableModel(data, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(defaultTableModel);
        defaultTableModel.fireTableDataChanged();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        facultyTab = new javax.swing.JPanel();
        facultyInfoLabelPane1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        facultyInfoFieldPane1 = new javax.swing.JPanel();
        facultyInfoIdField1 = new javax.swing.JTextField();
        facultyInfoNameField1 = new javax.swing.JTextField();
        facultyInfoDepField1 = new javax.swing.JTextField();
        studentTab = new javax.swing.JTabbedPane();
        studentASTab = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentASTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studentASIdField = new javax.swing.JTextField();
        StudentASNameField = new javax.swing.JTextField();
        studentASAgeField = new javax.swing.JTextField();
        jSplitPane1 = new javax.swing.JSplitPane();
        studentASSearchButton = new javax.swing.JButton();
        studentASClearButton = new javax.swing.JButton();
        studentASMajorCombo = new javax.swing.JComboBox();
        studentASLevelCombo = new javax.swing.JComboBox();
        studentMCTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentMCTable = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        studentMCIdField = new javax.swing.JTextField();
        studentMCNameField = new javax.swing.JTextField();
        studentMCMajorField = new javax.swing.JComboBox();
        studentMCLevelField = new javax.swing.JComboBox();
        studentMCAgeField = new javax.swing.JTextField();
        jSplitPane2 = new javax.swing.JSplitPane();
        studentMCSearchButton = new javax.swing.JButton();
        studentMCClearButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        courseNormSearchTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        courseSearchStudentCombo = new javax.swing.JComboBox();
        courseSearchE1Field = new javax.swing.JTextField();
        courseSEarchE2Field = new javax.swing.JTextField();
        courseSearchFField = new javax.swing.JTextField();
        jSplitPane3 = new javax.swing.JSplitPane();
        courseSearchButton = new javax.swing.JButton();
        courseClearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("My ID:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("My Name:");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("My Department:");

        javax.swing.GroupLayout facultyInfoLabelPane1Layout = new javax.swing.GroupLayout(facultyInfoLabelPane1);
        facultyInfoLabelPane1.setLayout(facultyInfoLabelPane1Layout);
        facultyInfoLabelPane1Layout.setHorizontalGroup(
            facultyInfoLabelPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
        );
        facultyInfoLabelPane1Layout.setVerticalGroup(
            facultyInfoLabelPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyInfoLabelPane1Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap(277, Short.MAX_VALUE))
        );

        facultyInfoIdField1.setEditable(false);

        facultyInfoNameField1.setEditable(false);

        facultyInfoDepField1.setEditable(false);

        javax.swing.GroupLayout facultyInfoFieldPane1Layout = new javax.swing.GroupLayout(facultyInfoFieldPane1);
        facultyInfoFieldPane1.setLayout(facultyInfoFieldPane1Layout);
        facultyInfoFieldPane1Layout.setHorizontalGroup(
            facultyInfoFieldPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultyInfoIdField1)
            .addComponent(facultyInfoNameField1)
            .addComponent(facultyInfoDepField1, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
        );
        facultyInfoFieldPane1Layout.setVerticalGroup(
            facultyInfoFieldPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyInfoFieldPane1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(facultyInfoIdField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facultyInfoNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facultyInfoDepField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout facultyTabLayout = new javax.swing.GroupLayout(facultyTab);
        facultyTab.setLayout(facultyTabLayout);
        facultyTabLayout.setHorizontalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addComponent(facultyInfoLabelPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(facultyInfoFieldPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        facultyTabLayout.setVerticalGroup(
            facultyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(facultyInfoLabelPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(facultyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(facultyInfoFieldPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("My info", facultyTab);

        studentASTable.setModel(new javax.swing.table.DefaultTableModel(
            studentData,
            studentColumns
        ));
        jScrollPane1.setViewportView(studentASTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jLabel1.setText("ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Major:");

        jLabel7.setText("Level:");

        jLabel8.setText("Age:");

        studentASSearchButton.setText("Search");
        studentASSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentASSearchButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(studentASSearchButton);

        studentASClearButton.setText("Clear");
        studentASClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentASClearButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(studentASClearButton);

        studentASMajorCombo.setModel(new javax.swing.DefaultComboBoxModel(majorList));

        studentASLevelCombo.setModel(new javax.swing.DefaultComboBoxModel(levelList));

        javax.swing.GroupLayout studentASTabLayout = new javax.swing.GroupLayout(studentASTab);
        studentASTab.setLayout(studentASTabLayout);
        studentASTabLayout.setHorizontalGroup(
            studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentASTabLayout.createSequentialGroup()
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentASTabLayout.createSequentialGroup()
                        .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentASIdField)
                            .addComponent(StudentASNameField)
                            .addComponent(studentASAgeField, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentASMajorCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(studentASLevelCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentASTabLayout.setVerticalGroup(
            studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(studentASTabLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentASIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(StudentASNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(studentASMajorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(studentASLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentASTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(studentASAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        studentTab.addTab("All Students", studentASTab);

        studentMCTable.setModel(new javax.swing.table.DefaultTableModel(
            studentData,
            studentColumns
        ));
        jScrollPane2.setViewportView(studentMCTable);

        jLabel9.setText("ID:");

        jLabel10.setText("Name:");

        jLabel11.setText("Major:");

        jLabel12.setText("Level:");

        jLabel13.setText("Age:");

        studentMCMajorField.setModel(new javax.swing.DefaultComboBoxModel(majorList));

        studentMCLevelField.setModel(new javax.swing.DefaultComboBoxModel(levelList));

        studentMCSearchButton.setText("Search");
        studentMCSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMCSearchButtonActionPerformed(evt);
            }
        });
        jSplitPane2.setLeftComponent(studentMCSearchButton);

        studentMCClearButton.setText("Clear");
        studentMCClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentMCClearButtonActionPerformed(evt);
            }
        });
        jSplitPane2.setRightComponent(studentMCClearButton);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentMCIdField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentMCNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentMCMajorField, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentMCLevelField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentMCAgeField, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addComponent(jSplitPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(studentMCIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(studentMCNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(studentMCMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(studentMCLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(studentMCAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout studentMCTabLayout = new javax.swing.GroupLayout(studentMCTab);
        studentMCTab.setLayout(studentMCTabLayout);
        studentMCTabLayout.setHorizontalGroup(
            studentMCTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentMCTabLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        studentMCTabLayout.setVerticalGroup(
            studentMCTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(studentMCTabLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        studentTab.addTab("Students in my Classes", studentMCTab);

        jTabbedPane1.addTab("Students", studentTab);

        courseNormSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            courseData,
            courseColumns
        ));
        jScrollPane3.setViewportView(courseNormSearchTable);

        jLabel14.setText("Student:");

        jLabel15.setText("Exam 1:");

        jLabel16.setText("Exam 2:");

        jLabel17.setText("Final:");

        courseSearchStudentCombo.setModel(new javax.swing.DefaultComboBoxModel(studentList));

        courseSearchButton.setText("Search");
        courseSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseSearchButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setLeftComponent(courseSearchButton);

        courseClearButton.setText("Clear");
        courseClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseClearButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setRightComponent(courseClearButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(courseSearchStudentCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 122, Short.MAX_VALUE)
                    .addComponent(courseSearchE1Field, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(courseSEarchE2Field)
                    .addComponent(courseSearchFField, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14)
                    .addComponent(courseSearchStudentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(courseSearchE1Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(courseSEarchE2Field, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(courseSearchFField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82)
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Courses", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentASSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentASSearchButtonActionPerformed
        // TODO add your handling code here:
        int id = -1;
        if (!studentASIdField.getText().equals("")) {
            id = Integer.parseInt(studentASIdField.getText());
        }
        String name = null;
        if (!StudentASNameField.getText().equals("")) {
            name = StudentASNameField.getText();
        }
        String major = null;
        if (studentASMajorCombo.getSelectedIndex() != 0) {
            major = (String) studentASMajorCombo.getSelectedItem();
        }
        String level = null;
        if (studentASLevelCombo.getSelectedIndex() != 0) {
            level = (String) studentASLevelCombo.getSelectedItem();
        }
        int age = -1;
        if (!studentASAgeField.getText().equals("")) {
            age = Integer.parseInt(studentASAgeField.getText());
        }

        Object[][] data;
        if (id == -1 && name == null && major == null && level == null && age == -1) {
            data = studentDatabase.searchStudent();
        } else {
            data = studentDatabase.searchStudent(id, name, major, level, age);
        }
        refresh(studentASTable, studentColumns, data);
    }//GEN-LAST:event_studentASSearchButtonActionPerformed

    private void studentASClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentASClearButtonActionPerformed
        // TODO add your handling code here:
        studentASIdField.setText("");
        StudentASNameField.setText("");
        studentASAgeField.setText("");
        studentASMajorCombo.setSelectedIndex(0);
        studentASLevelCombo.setSelectedIndex(0);
    }//GEN-LAST:event_studentASClearButtonActionPerformed

    private void studentMCSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMCSearchButtonActionPerformed
        // TODO add your handling code here:
        int id = -1;
        if (!studentMCIdField.getText().equals("")) {
            id = Integer.parseInt(studentMCIdField.getText());
        }
        String name = null;
        if (!studentMCNameField.getText().equals("")) {
            name = studentMCNameField.getText();
        }
        String major = null;
        if (studentMCMajorField.getSelectedIndex() != 0) {
            major = (String) studentMCMajorField.getSelectedItem();
        }
        String level = null;
        if (studentMCLevelField.getSelectedIndex() != 0) {
            level = (String) studentMCLevelField.getSelectedItem();
        }
        int age = -1;
        if (!studentMCAgeField.getText().equals("")) {
            age = Integer.parseInt(studentMCAgeField.getText());
        }

        Object[][] data;
        if (id == -1 && name == null && major == null && level == null && age == -1) {
            data = studentDatabase.searchEnrolled(fid);
        } else {
            data = studentDatabase.searchEnrolled(fid, id, name, major, level, age);
        }
        refresh(studentMCTable, studentColumns, data);
        studentMCClearButtonActionPerformed(null);

    }//GEN-LAST:event_studentMCSearchButtonActionPerformed

    private void studentMCClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentMCClearButtonActionPerformed
        // TODO add your handling code here:
        studentMCIdField.setText("");
        studentMCNameField.setText("");
        studentMCMajorField.setSelectedIndex(0);
        studentMCLevelField.setSelectedIndex(0);
        studentMCAgeField.setText("");
    }//GEN-LAST:event_studentMCClearButtonActionPerformed

    private void courseSearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseSearchButtonActionPerformed
        // TODO add your handling code here:
        String sName = null;
        if (courseSearchStudentCombo.getSelectedIndex() != 0) {
            sName = (String) courseSearchStudentCombo.getSelectedItem();
        }
        int exam1 = -1;
        if (courseSearchE1Field.getText().equals("")) {
            exam1 = Integer.parseInt(courseSearchE1Field.getText());
        }
        int exam2 = -1;
        if (courseSEarchE2Field.getText().equals("")) {
            exam2 = Integer.parseInt(courseSEarchE2Field.getText());
        }
        int finalExam = -1;
        if (courseSearchFField.getText().equals("")) {
            finalExam = Integer.parseInt(courseSearchFField.getText());
        }
        Object[][] data;
        if (sName == null && exam1 == -1 && exam2 == -1 && finalExam == -1) {
            data = generalDatabase.searchEnrolled(fid);
        } else {
            data = generalDatabase.searchEnrolled(fid, sName, exam1, exam2, finalExam);
        }

    }//GEN-LAST:event_courseSearchButtonActionPerformed

    private void courseClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseClearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FacultyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FacultyForm(Integer.parseInt(args[0])).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField StudentASNameField;
    private javax.swing.JButton courseClearButton;
    private javax.swing.JTable courseNormSearchTable;
    private javax.swing.JTextField courseSEarchE2Field;
    private javax.swing.JButton courseSearchButton;
    private javax.swing.JTextField courseSearchE1Field;
    private javax.swing.JTextField courseSearchFField;
    private javax.swing.JComboBox courseSearchStudentCombo;
    private javax.swing.JTextField facultyInfoDepField1;
    private javax.swing.JPanel facultyInfoFieldPane1;
    private javax.swing.JTextField facultyInfoIdField1;
    private javax.swing.JPanel facultyInfoLabelPane1;
    private javax.swing.JTextField facultyInfoNameField1;
    private javax.swing.JPanel facultyTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField studentASAgeField;
    private javax.swing.JButton studentASClearButton;
    private javax.swing.JTextField studentASIdField;
    private javax.swing.JComboBox studentASLevelCombo;
    private javax.swing.JComboBox studentASMajorCombo;
    private javax.swing.JButton studentASSearchButton;
    private javax.swing.JPanel studentASTab;
    private javax.swing.JTable studentASTable;
    private javax.swing.JTextField studentMCAgeField;
    private javax.swing.JButton studentMCClearButton;
    private javax.swing.JTextField studentMCIdField;
    private javax.swing.JComboBox studentMCLevelField;
    private javax.swing.JComboBox studentMCMajorField;
    private javax.swing.JTextField studentMCNameField;
    private javax.swing.JButton studentMCSearchButton;
    private javax.swing.JPanel studentMCTab;
    private javax.swing.JTable studentMCTable;
    private javax.swing.JTabbedPane studentTab;
    // End of variables declaration//GEN-END:variables
    private String[] majorList, levelList, courseList, studentList;
    private Object[][] studentData, courseData;
    private String[] studentColumns = {"ID", "Name", "Major", "Level", "Age"};
    private String[] courseColumns = {"Course", "Student", "Exam 1", "Exam 2", "Final"};
    private int fid, did;
    private String fName;
    private StudentDatabase studentDatabase;
    private FacultyDatabase facultyDatabase;
    private GeneralDatabase generalDatabase;
}
