/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs430.finalProject.frontEnd;

import cs430.finalProject.backEnd.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kreuter
 */
public class StaffForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public StaffForm() {
        studentDatabase = MainClassHolder.getStudentDatabase();
        staffDatabase = MainClassHolder.getStaffDatabase();
        facultyDatabase = MainClassHolder.getFacultyDatabase();
        generalDatabase = MainClassHolder.getGeneralDatabase();
        initComponents();
        tableValues = null;
        


    }

    public void initialSetupTable(JTable table, String[] columns, Object[][] values) {
        DefaultTableModel tableModel = new DefaultTableModel(values, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(tableModel);
    }

    /**
     * Draws table with new data.
     *
     * @param table   The table to be updated/redrawn.
     * @param columns The column headers to be used.
     * @param values  The values to populate the table with.
     */
    public void refresh(JTable table, String[] columns, Object[][] values) {

        DefaultTableModel tableModel = new DefaultTableModel(values, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        studentTab = new javax.swing.JTabbedPane();
        studentSearchTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentSearchTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        studentSearchIDField = new javax.swing.JTextField();
        studentSearchNameField = new javax.swing.JTextField();
        studentSearchMajorField = new javax.swing.JComboBox();
        studentSearchLevelField = new javax.swing.JComboBox();
        studentSearchAgeField = new javax.swing.JTextField();
        jSplitPane2 = new javax.swing.JSplitPane();
        studentSearchSubmitButton = new javax.swing.JButton();
        studentSearchClearButton = new javax.swing.JButton();
        studentAddTab = new javax.swing.JPanel();
        studentAddLabelPanel = new javax.swing.JPanel();
        studentAddIDLabel = new javax.swing.JLabel();
        studentAddNameLabel = new javax.swing.JLabel();
        studentAddMajorLabel = new javax.swing.JLabel();
        studentAddLevelLabel = new javax.swing.JLabel();
        studentAddAgeLabel = new javax.swing.JLabel();
        studentAddFieldPanel = new javax.swing.JPanel();
        studentAddIDField = new javax.swing.JTextField();
        studentAddNameField = new javax.swing.JTextField();
        studentAddMajorField = new javax.swing.JTextField();
        studentAddLevelCombo = new javax.swing.JComboBox();
        studentAddAgeField = new javax.swing.JTextField();
        studentAddMainLabel = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        studentAddSubmitButton = new javax.swing.JButton();
        studentAddClearButton = new javax.swing.JButton();
        studentUpdateTab = new javax.swing.JPanel();
        studentUpdateScrollPanel = new javax.swing.JScrollPane();
        studentUpdateTable = new javax.swing.JTable();
        studentUpdateMainLabel = new javax.swing.JLabel();
        studentUpdateLabelPanel = new javax.swing.JPanel();
        studentUpdateIDLabel = new javax.swing.JLabel();
        studentUpdateNameLabel = new javax.swing.JLabel();
        studentUpdateMajorLabel = new javax.swing.JLabel();
        studentUpdateLevelLabel = new javax.swing.JLabel();
        studentUpdateAgeLabel = new javax.swing.JLabel();
        studentUpdateFieldPanel = new javax.swing.JPanel();
        studentUpdateIDField = new javax.swing.JTextField();
        studentUpdateNameField = new javax.swing.JTextField();
        studentUpdateMajorField = new javax.swing.JTextField();
        studentUpdateAgeField = new javax.swing.JTextField();
        studentUpdateLevelSelect = new javax.swing.JComboBox();
        studentUpdateSplitPane = new javax.swing.JSplitPane();
        studentUpdateSubmitButton = new javax.swing.JButton();
        studentUpdateClearButton = new javax.swing.JButton();
        staffTab = new javax.swing.JTabbedPane();
        staffSearchTab = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        staffSearchTable = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        staffSearchIDField = new javax.swing.JTextField();
        staffSearchNameField = new javax.swing.JTextField();
        staffSearchDeptCombo = new javax.swing.JComboBox();
        jSplitPane3 = new javax.swing.JSplitPane();
        staffSearchSubmitButton = new javax.swing.JButton();
        staffSearchClearButton = new javax.swing.JButton();
        staffAddTab = new javax.swing.JPanel();
        staffAddLabelPanel = new javax.swing.JPanel();
        staffAddIdLabel = new javax.swing.JLabel();
        staffAddNameLabel = new javax.swing.JLabel();
        staffAddDeptIdLabel = new javax.swing.JLabel();
        staffAddFieldPanel = new javax.swing.JPanel();
        staffAddIdField = new javax.swing.JTextField();
        staffAddNameField = new javax.swing.JTextField();
        staffAddDeptCombo = new javax.swing.JComboBox();
        staffAddMainLabel = new javax.swing.JLabel();
        staffAddSplitPane = new javax.swing.JSplitPane();
        staffAddSubmitButton = new javax.swing.JButton();
        staffAddClearButton = new javax.swing.JButton();
        staffUpdateTab = new javax.swing.JPanel();
        staffUpdateScrollPanel = new javax.swing.JScrollPane();
        staffUpdateTable = new javax.swing.JTable();
        staffUpdateMainLabel = new javax.swing.JLabel();
        staffUpdateLabelPanel = new javax.swing.JPanel();
        staffUpdateIdLabel = new javax.swing.JLabel();
        staffUpdateNameLabel = new javax.swing.JLabel();
        staffUpdateDeptLabel = new javax.swing.JLabel();
        staffUpdateFieldPanel = new javax.swing.JPanel();
        staffUpdateIdField = new javax.swing.JTextField();
        staffUpdateNameField = new javax.swing.JTextField();
        staffUpdateDeptCombo = new javax.swing.JComboBox();
        staffUpdateSplitPane = new javax.swing.JSplitPane();
        staffUpdateSubmitButton = new javax.swing.JButton();
        staffUpdateClearButton = new javax.swing.JButton();
        facultyTab = new javax.swing.JTabbedPane();
        facultySearchTab = new javax.swing.JTabbedPane();
        facultyAddTab = new javax.swing.JTabbedPane();
        facultyUpdateTab = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Staff Form");
        setName("staffAccessForm"); // NOI18N

        studentSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            studentDatabase.searchStudent(),
            new String [] {
                "ID", "Name", "Major", "Level", "Age"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentSearchTable);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Major");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Level");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        studentSearchMajorField.setModel(new javax.swing.DefaultComboBoxModel(studentDatabase.getMajors()));

        studentSearchLevelField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Any", "Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentSearchAgeField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentSearchLevelField, javax.swing.GroupLayout.Alignment.TRAILING, 0, 161, Short.MAX_VALUE)
                    .addComponent(studentSearchMajorField, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentSearchNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentSearchIDField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(studentSearchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        studentSearchSubmitButton.setText("Search");
        studentSearchSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchSubmitButtonActionPerformed(evt);
            }
        });
        jSplitPane2.setLeftComponent(studentSearchSubmitButton);

        studentSearchClearButton.setText("Clear");
        studentSearchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchClearButtonActionPerformed(evt);
            }
        });
        jSplitPane2.setRightComponent(studentSearchClearButton);

        javax.swing.GroupLayout studentSearchTabLayout = new javax.swing.GroupLayout(studentSearchTab);
        studentSearchTab.setLayout(studentSearchTabLayout);
        studentSearchTabLayout.setHorizontalGroup(
            studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentSearchTabLayout.createSequentialGroup()
                .addGroup(studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(studentSearchTabLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(studentSearchTabLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
        );
        studentSearchTabLayout.setVerticalGroup(
            studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSearchTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(studentSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentTab.addTab("Search", studentSearchTab);

        studentAddIDLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddIDLabel.setText("ID:");

        studentAddNameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddNameLabel.setText("Name:");

        studentAddMajorLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddMajorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddMajorLabel.setText("Major:");

        studentAddLevelLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddLevelLabel.setText("Level:");

        studentAddAgeLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddAgeLabel.setText("Age:");

        javax.swing.GroupLayout studentAddLabelPanelLayout = new javax.swing.GroupLayout(studentAddLabelPanel);
        studentAddLabelPanel.setLayout(studentAddLabelPanelLayout);
        studentAddLabelPanelLayout.setHorizontalGroup(
            studentAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddLabelPanelLayout.createSequentialGroup()
                .addGroup(studentAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(studentAddAgeLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAddLevelLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAddMajorLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAddNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(studentAddIDLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        studentAddLabelPanelLayout.setVerticalGroup(
            studentAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddLabelPanelLayout.createSequentialGroup()
                .addComponent(studentAddIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddMajorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        studentAddLevelCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD" }));

        javax.swing.GroupLayout studentAddFieldPanelLayout = new javax.swing.GroupLayout(studentAddFieldPanel);
        studentAddFieldPanel.setLayout(studentAddFieldPanelLayout);
        studentAddFieldPanelLayout.setHorizontalGroup(
            studentAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentAddIDField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(studentAddNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addComponent(studentAddMajorField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(studentAddLevelCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentAddAgeField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        studentAddFieldPanelLayout.setVerticalGroup(
            studentAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddFieldPanelLayout.createSequentialGroup()
                .addComponent(studentAddIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        studentAddMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        studentAddMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentAddMainLabel.setText("Add a new student");

        studentAddSubmitButton.setText("Submit");
        studentAddSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddSubmitButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(studentAddSubmitButton);

        studentAddClearButton.setText("Clear");
        studentAddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddClearButtonActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(studentAddClearButton);

        javax.swing.GroupLayout studentAddTabLayout = new javax.swing.GroupLayout(studentAddTab);
        studentAddTab.setLayout(studentAddTabLayout);
        studentAddTabLayout.setHorizontalGroup(
            studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddTabLayout.createSequentialGroup()
                .addComponent(studentAddLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(studentAddMainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(studentAddTabLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentAddTabLayout.setVerticalGroup(
            studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddTabLayout.createSequentialGroup()
                .addComponent(studentAddMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentAddLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        studentTab.addTab("Add", studentAddTab);

        studentUpdateTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentUpdateTabMousePressed(evt);
            }
        });

        studentUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
            studentDatabase.searchStudent(),
            new String [] {
                "ID", "Name", "Major", "Level", "Age"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentUpdateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentUpdateTableMousePressed(evt);
            }
        });
        studentUpdateScrollPanel.setViewportView(studentUpdateTable);

        studentUpdateMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        studentUpdateMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentUpdateMainLabel.setText("Update a student entry");

        studentUpdateIDLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateIDLabel.setText("ID:");

        studentUpdateNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateNameLabel.setText("Name:");

        studentUpdateMajorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateMajorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateMajorLabel.setText("Major:");

        studentUpdateLevelLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateLevelLabel.setText("Level");

        studentUpdateAgeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateAgeLabel.setText("Age");

        javax.swing.GroupLayout studentUpdateLabelPanelLayout = new javax.swing.GroupLayout(studentUpdateLabelPanel);
        studentUpdateLabelPanel.setLayout(studentUpdateLabelPanelLayout);
        studentUpdateLabelPanelLayout.setHorizontalGroup(
            studentUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentUpdateIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentUpdateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addComponent(studentUpdateMajorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentUpdateLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(studentUpdateAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentUpdateLabelPanelLayout.setVerticalGroup(
            studentUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentUpdateLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentUpdateIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateMajorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentUpdateIDField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateNameField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateMajorField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateAgeField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateLevelSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD" }));

        javax.swing.GroupLayout studentUpdateFieldPanelLayout = new javax.swing.GroupLayout(studentUpdateFieldPanel);
        studentUpdateFieldPanel.setLayout(studentUpdateFieldPanelLayout);
        studentUpdateFieldPanelLayout.setHorizontalGroup(
            studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentUpdateFieldPanelLayout.createSequentialGroup()
                .addGroup(studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentUpdateIDField)
                    .addComponent(studentUpdateNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(studentUpdateMajorField)
                    .addComponent(studentUpdateAgeField)
                    .addComponent(studentUpdateLevelSelect, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        studentUpdateFieldPanelLayout.setVerticalGroup(
            studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentUpdateFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentUpdateIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateLevelSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        studentUpdateSubmitButton.setText("Submit");
        studentUpdateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUpdateSubmitButtonActionPerformed(evt);
            }
        });
        studentUpdateSplitPane.setLeftComponent(studentUpdateSubmitButton);

        studentUpdateClearButton.setText("Clear");
        studentUpdateClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUpdateClearButtonActionPerformed(evt);
            }
        });
        studentUpdateSplitPane.setRightComponent(studentUpdateClearButton);

        javax.swing.GroupLayout studentUpdateTabLayout = new javax.swing.GroupLayout(studentUpdateTab);
        studentUpdateTab.setLayout(studentUpdateTabLayout);
        studentUpdateTabLayout.setHorizontalGroup(
            studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentUpdateScrollPanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentUpdateLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(studentUpdateTabLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(studentUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        studentUpdateTabLayout.setVerticalGroup(
            studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addComponent(studentUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentUpdateLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentUpdateFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        studentTab.addTab("Update", studentUpdateTab);

        jTabbedPane1.addTab("Student", studentTab);

        staffSearchTable.setModel(new javax.swing.table.DefaultTableModel(
            staffDatabase.staffSearch(),
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(staffSearchTable);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Name");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Department ID");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(146, Short.MAX_VALUE))
        );

        staffSearchDeptCombo.setModel(new javax.swing.DefaultComboBoxModel(generalDatabase.getDepartmentNames()));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffSearchDeptCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffSearchNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(staffSearchIDField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(staffSearchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffSearchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffSearchDeptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        staffSearchSubmitButton.setText("Search");
        staffSearchSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffSearchSubmitButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setLeftComponent(staffSearchSubmitButton);

        staffSearchClearButton.setText("Clear");
        staffSearchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffSearchClearButtonActionPerformed(evt);
            }
        });
        jSplitPane3.setRightComponent(staffSearchClearButton);

        javax.swing.GroupLayout staffSearchTabLayout = new javax.swing.GroupLayout(staffSearchTab);
        staffSearchTab.setLayout(staffSearchTabLayout);
        staffSearchTabLayout.setHorizontalGroup(
            staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffSearchTabLayout.createSequentialGroup()
                .addGroup(staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffSearchTabLayout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(staffSearchTabLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE))
        );
        staffSearchTabLayout.setVerticalGroup(
            staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSearchTabLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 45, Short.MAX_VALUE))
            .addGroup(staffSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffTab.addTab("Search", staffSearchTab);

        staffAddIdLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        staffAddIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffAddIdLabel.setText("ID:");

        staffAddNameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        staffAddNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffAddNameLabel.setText("Name:");

        staffAddDeptIdLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        staffAddDeptIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffAddDeptIdLabel.setText("Department:");

        javax.swing.GroupLayout staffAddLabelPanelLayout = new javax.swing.GroupLayout(staffAddLabelPanel);
        staffAddLabelPanel.setLayout(staffAddLabelPanelLayout);
        staffAddLabelPanelLayout.setHorizontalGroup(
            staffAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffAddLabelPanelLayout.createSequentialGroup()
                .addGroup(staffAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(staffAddDeptIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffAddNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                    .addComponent(staffAddIdLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 100, Short.MAX_VALUE))
        );
        staffAddLabelPanelLayout.setVerticalGroup(
            staffAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffAddLabelPanelLayout.createSequentialGroup()
                .addComponent(staffAddIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddDeptIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(177, Short.MAX_VALUE))
        );

        staffAddDeptCombo.setModel(new javax.swing.DefaultComboBoxModel(generalDatabase.getDepartmentNames()));

        javax.swing.GroupLayout staffAddFieldPanelLayout = new javax.swing.GroupLayout(staffAddFieldPanel);
        staffAddFieldPanel.setLayout(staffAddFieldPanelLayout);
        staffAddFieldPanelLayout.setHorizontalGroup(
            staffAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffAddIdField, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(staffAddNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
            .addComponent(staffAddDeptCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        staffAddFieldPanelLayout.setVerticalGroup(
            staffAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffAddFieldPanelLayout.createSequentialGroup()
                .addComponent(staffAddIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddDeptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        staffAddMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        staffAddMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffAddMainLabel.setText("Add a new staff member");

        staffAddSubmitButton.setText("Submit");
        staffAddSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffAddSubmitButtonActionPerformed(evt);
            }
        });
        staffAddSplitPane.setLeftComponent(staffAddSubmitButton);

        staffAddClearButton.setText("Clear");
        staffAddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffAddClearButtonActionPerformed(evt);
            }
        });
        staffAddSplitPane.setRightComponent(staffAddClearButton);

        javax.swing.GroupLayout staffAddTabLayout = new javax.swing.GroupLayout(staffAddTab);
        staffAddTab.setLayout(staffAddTabLayout);
        staffAddTabLayout.setHorizontalGroup(
            staffAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffAddTabLayout.createSequentialGroup()
                .addComponent(staffAddLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(staffAddMainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(staffAddTabLayout.createSequentialGroup()
                .addGap(341, 341, 341)
                .addComponent(staffAddSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffAddTabLayout.setVerticalGroup(
            staffAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffAddTabLayout.createSequentialGroup()
                .addComponent(staffAddMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staffAddLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(staffAddSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        staffTab.addTab("Add", staffAddTab);

        staffUpdateTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffUpdateTabMousePressed(evt);
            }
        });

        staffUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
            staffDatabase.staffSearch(),
            new String [] {
                "ID", "Name", "Department"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        staffUpdateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                staffUpdateTableMousePressed(evt);
            }
        });
        staffUpdateScrollPanel.setViewportView(staffUpdateTable);

        staffUpdateMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        staffUpdateMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        staffUpdateMainLabel.setText("Update a staff entry");

        staffUpdateIdLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        staffUpdateIdLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffUpdateIdLabel.setText("ID:");

        staffUpdateNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        staffUpdateNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffUpdateNameLabel.setText("Name:");

        staffUpdateDeptLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        staffUpdateDeptLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        staffUpdateDeptLabel.setText("Major:");

        javax.swing.GroupLayout staffUpdateLabelPanelLayout = new javax.swing.GroupLayout(staffUpdateLabelPanel);
        staffUpdateLabelPanel.setLayout(staffUpdateLabelPanelLayout);
        staffUpdateLabelPanelLayout.setHorizontalGroup(
            staffUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffUpdateIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(staffUpdateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
            .addComponent(staffUpdateDeptLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        staffUpdateLabelPanelLayout.setVerticalGroup(
            staffUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffUpdateLabelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffUpdateIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateDeptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        staffUpdateIdField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        staffUpdateNameField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        staffUpdateDeptCombo.setModel(new javax.swing.DefaultComboBoxModel(generalDatabase.getDepartmentNames()));

        javax.swing.GroupLayout staffUpdateFieldPanelLayout = new javax.swing.GroupLayout(staffUpdateFieldPanel);
        staffUpdateFieldPanel.setLayout(staffUpdateFieldPanelLayout);
        staffUpdateFieldPanelLayout.setHorizontalGroup(
            staffUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffUpdateFieldPanelLayout.createSequentialGroup()
                .addGroup(staffUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(staffUpdateIdField)
                    .addComponent(staffUpdateNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .addComponent(staffUpdateDeptCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        staffUpdateFieldPanelLayout.setVerticalGroup(
            staffUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffUpdateFieldPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffUpdateIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateDeptCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        staffUpdateSubmitButton.setText("Submit");
        staffUpdateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffUpdateSubmitButtonActionPerformed(evt);
            }
        });
        staffUpdateSplitPane.setLeftComponent(staffUpdateSubmitButton);

        staffUpdateClearButton.setText("Clear");
        staffUpdateClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                staffUpdateClearButtonActionPerformed(evt);
            }
        });
        staffUpdateSplitPane.setRightComponent(staffUpdateClearButton);

        javax.swing.GroupLayout staffUpdateTabLayout = new javax.swing.GroupLayout(staffUpdateTab);
        staffUpdateTab.setLayout(staffUpdateTabLayout);
        staffUpdateTabLayout.setHorizontalGroup(
            staffUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffUpdateScrollPanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffUpdateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(staffUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffUpdateTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(staffUpdateLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(staffUpdateTabLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(staffUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffUpdateTabLayout.setVerticalGroup(
            staffUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffUpdateTabLayout.createSequentialGroup()
                .addComponent(staffUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(staffUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(staffUpdateLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(staffUpdateFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(staffUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        staffTab.addTab("Update", staffUpdateTab);

        jTabbedPane1.addTab("Staff", staffTab);

        facultyTab.addTab("Search", facultySearchTab);
        facultyTab.addTab("Add", facultyAddTab);
        facultyTab.addTab("Update", facultyUpdateTab);

        jTabbedPane1.addTab("Faculty", facultyTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentUpdateTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentUpdateTabMousePressed
        // TODO add your handling code here:
        String[] columns = {"ID", "Name", "Major", "Level", "Age"};
        refresh(studentUpdateTable, columns, studentDatabase.searchStudent());
    }//GEN-LAST:event_studentUpdateTabMousePressed

    private void studentUpdateClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUpdateClearButtonActionPerformed
        // TODO add your handling code here:
        studentUpdateIDField.setText("");
        studentUpdateNameField.setText("");
        studentUpdateMajorField.setText("");
        studentUpdateLevelSelect.setSelectedIndex(0);
        studentUpdateAgeField.setText("");
        oldSid = -1;
    }//GEN-LAST:event_studentUpdateClearButtonActionPerformed

    private void studentUpdateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUpdateSubmitButtonActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(studentUpdateIDField.getText());
        String name = studentUpdateNameField.getText();
        String major = studentUpdateMajorField.getText();
        String level = (String) studentUpdateLevelSelect.getSelectedItem();
        int age = Integer.parseInt(studentUpdateAgeField.getText());

        studentDatabase.updateStudent(oldSid, id, name, major, level, age);
        String[] columns = {"ID", "Name", "Major", "Level", "Age"};
        refresh(studentUpdateTable, columns, studentDatabase.searchStudent());
        studentUpdateClearButtonActionPerformed(null);

    }//GEN-LAST:event_studentUpdateSubmitButtonActionPerformed

    private void studentUpdateTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentUpdateTableMousePressed
        // TODO add your handling code here:
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();

        int id = (Integer) target.getValueAt(row, 0);
        String name = (String) target.getValueAt(row, 1);
        String major = (String) target.getValueAt(row, 2);
        String level = (String) target.getValueAt(row, 3);
        int age = (Integer) target.getValueAt(row, 4);

        studentUpdateIDField.setText(id + "");
        oldSid = id;
        studentUpdateNameField.setText(name);
        studentUpdateMajorField.setText(major);
        studentUpdateLevelSelect.setSelectedItem(level);
        studentUpdateAgeField.setText(age + "");
    }//GEN-LAST:event_studentUpdateTableMousePressed

    private void studentAddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddClearButtonActionPerformed
        studentAddIDField.setText("");
        studentAddNameField.setText("");
        studentAddMajorField.setText("");
        studentAddLevelCombo.setSelectedIndex(0);
        studentAddAgeField.setText("");
    }//GEN-LAST:event_studentAddClearButtonActionPerformed

    private void studentAddSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddSubmitButtonActionPerformed
        int id, age;
        try {
            id = Integer.parseInt(studentAddIDField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You must put in a valid number for ID");
            return;
        }
        String name = studentAddNameField.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a valid name");
            return;
        }
        String major = studentAddMajorField.getText();
        if (major.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a valid major");
            return;
        }
        String level = (String) studentAddLevelCombo.getSelectedItem();
        try {
            age = Integer.parseInt(studentAddAgeField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You must put in a valid number for age");
            return;
        }
        String[] columns = {"ID", "Name", "Major", "Level", "Age"};
        studentDatabase.insertStudent(id, name, major, level, age);
        refresh(studentUpdateTable, columns, studentDatabase.searchStudent());
        refresh(studentSearchTable, columns, studentDatabase.searchStudent());
        studentAddClearButtonActionPerformed(null);
    }//GEN-LAST:event_studentAddSubmitButtonActionPerformed

    private void studentSearchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchClearButtonActionPerformed
        // TODO add your handling code here:
        studentSearchIDField.setText("");
        studentSearchNameField.setText("");
        studentSearchMajorField.setSelectedIndex(0);
        studentSearchLevelField.setSelectedIndex(0);
        studentSearchAgeField.setText("");
        // TODO add search with no items
    }//GEN-LAST:event_studentSearchClearButtonActionPerformed

    private void studentSearchSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchSubmitButtonActionPerformed
        // TODO add your handling code here:

        String sid = studentSearchIDField.getText();
        int id = -1;
        if (!sid.equals("")) {
            id = Integer.parseInt(sid);
        }
        String name = studentSearchNameField.getText();
        if (name.equals("")) {
            name = null;
        }
        String major = (String) studentSearchMajorField.getSelectedItem();
        if (studentSearchMajorField.getSelectedIndex() == 0) {
            major = null;
        }
        String level = (String) studentSearchLevelField.getSelectedItem();
        if (studentSearchLevelField.getSelectedIndex() == 0) {
            level = null;
        }
        String sAge = studentSearchAgeField.getText();
        int age = -1;
        if (!sAge.equals("")) {
            age = Integer.parseInt(sAge);
        }
        String[] columns = {"ID", "Name", "Major", "Level", "Age"};

        Object[][] newData;
        if (id == -1 && name == null && major == null && level == null && age == -1) {
            newData = studentDatabase.searchStudent();
        } else {
            newData = studentDatabase.searchStudent(id, name, major, level, age);
        }
        refresh(studentSearchTable, columns, newData);
    }//GEN-LAST:event_studentSearchSubmitButtonActionPerformed

    private void staffSearchSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffSearchSubmitButtonActionPerformed
        // TODO add your handling code here:
        int id;
        try {
            id = Integer.parseInt(staffSearchIDField.getText());
        } catch (NumberFormatException e) {
            id = -1;
        }
        String name = staffSearchNameField.getText();
        if (name.equals("")) {
            name = null;
        }
        String deptName = null;
        if (staffSearchDeptCombo.getSelectedIndex() != 0) {
            deptName = (String) staffSearchDeptCombo.getSelectedItem();
        }

        String[] columns = {"ID", "Name", "Department"};
        if (id == -1 && name == null && deptName == null) {
            refresh(staffSearchTable, columns, staffDatabase.staffSearch());
        } else {
            refresh(staffSearchTable, columns, staffDatabase.staffSearch(id, name, deptName));
        }
        staffSearchClearButtonActionPerformed(null);

    }//GEN-LAST:event_staffSearchSubmitButtonActionPerformed

    private void staffSearchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffSearchClearButtonActionPerformed
        // TODO add your handling code here:
        staffSearchIDField.setText("");
        staffSearchNameField.setText("");
        staffSearchDeptCombo.setSelectedIndex(0);
    }//GEN-LAST:event_staffSearchClearButtonActionPerformed

    private void staffAddSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffAddSubmitButtonActionPerformed
        // TODO add your handling code here:
        int id;
        try {
            id = Integer.parseInt(staffAddIdField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You must input a valid number for the ID");
            return;
        }
        String name = staffAddNameField.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a name");
            return;
        }
        int deptId = generalDatabase.getDepartmentId((String) staffAddDeptCombo.getSelectedItem());

        staffDatabase.insertStaff(id, name, deptId);


    }//GEN-LAST:event_staffAddSubmitButtonActionPerformed

    private void staffAddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffAddClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffAddClearButtonActionPerformed

    private void staffUpdateTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffUpdateTableMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUpdateTableMousePressed

    private void staffUpdateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffUpdateSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUpdateSubmitButtonActionPerformed

    private void staffUpdateClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_staffUpdateClearButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUpdateClearButtonActionPerformed

    private void staffUpdateTabMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffUpdateTabMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_staffUpdateTabMousePressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    protected void getStudenTable(){
        //tableValues = ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane facultyAddTab;
    private javax.swing.JTabbedPane facultySearchTab;
    private javax.swing.JTabbedPane facultyTab;
    private javax.swing.JTabbedPane facultyUpdateTab;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton staffAddClearButton;
    private javax.swing.JComboBox staffAddDeptCombo;
    private javax.swing.JLabel staffAddDeptIdLabel;
    private javax.swing.JPanel staffAddFieldPanel;
    private javax.swing.JTextField staffAddIdField;
    private javax.swing.JLabel staffAddIdLabel;
    private javax.swing.JPanel staffAddLabelPanel;
    private javax.swing.JLabel staffAddMainLabel;
    private javax.swing.JTextField staffAddNameField;
    private javax.swing.JLabel staffAddNameLabel;
    private javax.swing.JSplitPane staffAddSplitPane;
    private javax.swing.JButton staffAddSubmitButton;
    private javax.swing.JPanel staffAddTab;
    private javax.swing.JButton staffSearchClearButton;
    private javax.swing.JComboBox staffSearchDeptCombo;
    private javax.swing.JTextField staffSearchIDField;
    private javax.swing.JTextField staffSearchNameField;
    private javax.swing.JButton staffSearchSubmitButton;
    private javax.swing.JPanel staffSearchTab;
    private javax.swing.JTable staffSearchTable;
    private javax.swing.JTabbedPane staffTab;
    private javax.swing.JButton staffUpdateClearButton;
    private javax.swing.JComboBox staffUpdateDeptCombo;
    private javax.swing.JLabel staffUpdateDeptLabel;
    private javax.swing.JPanel staffUpdateFieldPanel;
    private javax.swing.JTextField staffUpdateIdField;
    private javax.swing.JLabel staffUpdateIdLabel;
    private javax.swing.JPanel staffUpdateLabelPanel;
    private javax.swing.JLabel staffUpdateMainLabel;
    private javax.swing.JTextField staffUpdateNameField;
    private javax.swing.JLabel staffUpdateNameLabel;
    private javax.swing.JScrollPane staffUpdateScrollPanel;
    private javax.swing.JSplitPane staffUpdateSplitPane;
    private javax.swing.JButton staffUpdateSubmitButton;
    private javax.swing.JPanel staffUpdateTab;
    private javax.swing.JTable staffUpdateTable;
    private javax.swing.JTextField studentAddAgeField;
    private javax.swing.JLabel studentAddAgeLabel;
    private javax.swing.JButton studentAddClearButton;
    private javax.swing.JPanel studentAddFieldPanel;
    private javax.swing.JTextField studentAddIDField;
    private javax.swing.JLabel studentAddIDLabel;
    private javax.swing.JPanel studentAddLabelPanel;
    private javax.swing.JComboBox studentAddLevelCombo;
    private javax.swing.JLabel studentAddLevelLabel;
    private javax.swing.JLabel studentAddMainLabel;
    private javax.swing.JTextField studentAddMajorField;
    private javax.swing.JLabel studentAddMajorLabel;
    private javax.swing.JTextField studentAddNameField;
    private javax.swing.JLabel studentAddNameLabel;
    private javax.swing.JButton studentAddSubmitButton;
    private javax.swing.JPanel studentAddTab;
    private javax.swing.JTextField studentSearchAgeField;
    private javax.swing.JButton studentSearchClearButton;
    private javax.swing.JTextField studentSearchIDField;
    private javax.swing.JComboBox studentSearchLevelField;
    private javax.swing.JComboBox studentSearchMajorField;
    private javax.swing.JTextField studentSearchNameField;
    private javax.swing.JButton studentSearchSubmitButton;
    private javax.swing.JPanel studentSearchTab;
    private javax.swing.JTable studentSearchTable;
    private javax.swing.JTabbedPane studentTab;
    private javax.swing.JTextField studentUpdateAgeField;
    private javax.swing.JLabel studentUpdateAgeLabel;
    private javax.swing.JButton studentUpdateClearButton;
    private javax.swing.JPanel studentUpdateFieldPanel;
    private javax.swing.JTextField studentUpdateIDField;
    private javax.swing.JLabel studentUpdateIDLabel;
    private javax.swing.JPanel studentUpdateLabelPanel;
    private javax.swing.JLabel studentUpdateLevelLabel;
    private javax.swing.JComboBox studentUpdateLevelSelect;
    private javax.swing.JLabel studentUpdateMainLabel;
    private javax.swing.JTextField studentUpdateMajorField;
    private javax.swing.JLabel studentUpdateMajorLabel;
    private javax.swing.JTextField studentUpdateNameField;
    private javax.swing.JLabel studentUpdateNameLabel;
    private javax.swing.JScrollPane studentUpdateScrollPanel;
    private javax.swing.JSplitPane studentUpdateSplitPane;
    private javax.swing.JButton studentUpdateSubmitButton;
    private javax.swing.JPanel studentUpdateTab;
    private javax.swing.JTable studentUpdateTable;
    // End of variables declaration//GEN-END:variables
    private Object[][] tableValues;
    private StudentDatabase studentDatabase;
    private FacultyDatabase facultyDatabase;
    private StaffDatabase staffDatabase;
    private GeneralDatabase generalDatabase;
    private int oldSid;
}
