/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs430.finalProject.frontEnd;

import cs430.finalProject.backEnd.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author kreuter
 */
public class StaffForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public StaffForm() {
        studentDatabase = MainClassHolder.getStudentDatabase();
        staffDatabase = MainClassHolder.getStaffDatabase();
        facultyDatabase = MainClassHolder.getFacultyDatabase();
        generalDatabase = MainClassHolder.getGeneralDatabase();
        initComponents();
        tableValues = null;
        studentUpdateOldSid.setVisible(false);


    }

    public void initialSetupTable(JTable table, String[] columns, Object[][] values) {
        DefaultTableModel tableModel = new DefaultTableModel(values, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(tableModel);
    }

    /**
     * Draws table with new data.
     *
     * @param table   The table to be updated/redrawn.
     * @param columns The column headers to be used.
     * @param values  The values to populate the table with.
     */
    public void refresh(JTable table, String[] columns, Object[][] values) {

        DefaultTableModel tableModel = new DefaultTableModel(values, columns) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        table.setModel(tableModel);
        tableModel.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        studentTab = new javax.swing.JTabbedPane();
        studentSearchTab = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentSearchTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        studentSearchIDField = new javax.swing.JTextField();
        studentSearchNameField = new javax.swing.JTextField();
        studentSearchMajorField = new javax.swing.JComboBox();
        studentSearchLevelField = new javax.swing.JComboBox();
        studentSearchAgeField = new javax.swing.JTextField();
        studentSearchSubmitButton = new javax.swing.JButton();
        studentSearchClearButton = new javax.swing.JButton();
        studentAddTab = new javax.swing.JPanel();
        studentAddLabelPanel = new javax.swing.JPanel();
        studentAddIDLabel = new javax.swing.JLabel();
        studentAddNameLabel = new javax.swing.JLabel();
        studentAddMajorLabel = new javax.swing.JLabel();
        studentAddLevelLabel = new javax.swing.JLabel();
        studentAddAgeLabel = new javax.swing.JLabel();
        studentAddFieldPanel = new javax.swing.JPanel();
        studentAddIDField = new javax.swing.JTextField();
        studentAddNameField = new javax.swing.JTextField();
        studentAddMajorField = new javax.swing.JTextField();
        studentAddLevelCombo = new javax.swing.JComboBox();
        studentAddAgeField = new javax.swing.JTextField();
        studentAddMainLabel = new javax.swing.JLabel();
        studentAddSubmitButton = new javax.swing.JButton();
        studentAddClearButton = new javax.swing.JButton();
        studentUpdateTab = new javax.swing.JPanel();
        studentUpdateScrollPanel = new javax.swing.JScrollPane();
        studentUpdateTable = new javax.swing.JTable();
        studentUpdateMainLabel = new javax.swing.JLabel();
        studentUpdateLabelPanel = new javax.swing.JPanel();
        studentUpdateIDLabel = new javax.swing.JLabel();
        studentUpdateNameLabel = new javax.swing.JLabel();
        studentUpdateMajorLabel = new javax.swing.JLabel();
        studentUpdateLevelLabel = new javax.swing.JLabel();
        studentUpdateAgeLabel = new javax.swing.JLabel();
        studentUpdateFieldPanel = new javax.swing.JPanel();
        studentUpdateIDField = new javax.swing.JTextField();
        studentUpdateNameField = new javax.swing.JTextField();
        studentUpdateMajorField = new javax.swing.JTextField();
        studentUpdateAgeField = new javax.swing.JTextField();
        studentUpdateLevelSelect = new javax.swing.JComboBox();
        studentUpdateSplitPane = new javax.swing.JSplitPane();
        studentUpdateSubmitButton = new javax.swing.JButton();
        studentUpdateClearButton = new javax.swing.JButton();
        studentUpdateOldSid = new javax.swing.JTextField();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        staffSearchTab = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        studentSearchIDField1 = new javax.swing.JTextField();
        studentSearchNameField1 = new javax.swing.JTextField();
        studentSearchMajorField1 = new javax.swing.JComboBox();
        studentSearchLevelField1 = new javax.swing.JComboBox();
        studentSearchAgeField1 = new javax.swing.JTextField();
        studentSearchSubmitButton1 = new javax.swing.JButton();
        studentSearchClearButton1 = new javax.swing.JButton();
        jTabbedPane4 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("staffAccessForm"); // NOI18N

        studentSearchTable.setModel(new javax.swing.table.DefaultTableModel(
                studentDatabase.searchStudent(),
                new String[]{
                        "ID", "Name", "Major", "Level", "Age"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentSearchTable);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Name");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Major");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Level");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Age");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSearchMajorField.setModel(new javax.swing.DefaultComboBoxModel(studentDatabase.getMajors()));

        studentSearchLevelField.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Any", "Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD"}));

        studentSearchSubmitButton.setText("Search");
        studentSearchSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchSubmitButtonActionPerformed(evt);
            }
        });

        studentSearchClearButton.setText("Clear");
        studentSearchClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentSearchAgeField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(studentSearchLevelField, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentSearchMajorField, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentSearchNameField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(studentSearchIDField, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(studentSearchSubmitButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(studentSearchClearButton)))
                                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(studentSearchIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentSearchSubmitButton)
                    .addComponent(studentSearchClearButton))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout studentSearchTabLayout = new javax.swing.GroupLayout(studentSearchTab);
        studentSearchTab.setLayout(studentSearchTabLayout);
        studentSearchTabLayout.setHorizontalGroup(
                studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentSearchTabLayout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );
        studentSearchTabLayout.setVerticalGroup(
            studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(studentSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(studentSearchTabLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 44, Short.MAX_VALUE))
        );

        studentTab.addTab("Search", studentSearchTab);

        studentAddIDLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddIDLabel.setText("ID:");

        studentAddNameLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddNameLabel.setText("Name:");

        studentAddMajorLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddMajorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddMajorLabel.setText("Major:");

        studentAddLevelLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddLevelLabel.setText("Level:");

        studentAddAgeLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        studentAddAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentAddAgeLabel.setText("Age:");

        javax.swing.GroupLayout studentAddLabelPanelLayout = new javax.swing.GroupLayout(studentAddLabelPanel);
        studentAddLabelPanel.setLayout(studentAddLabelPanelLayout);
        studentAddLabelPanelLayout.setHorizontalGroup(
                studentAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(studentAddAgeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentAddNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                        .addComponent(studentAddIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentAddMajorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentAddLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentAddLabelPanelLayout.setVerticalGroup(
                studentAddLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentAddLabelPanelLayout.createSequentialGroup()
                                .addComponent(studentAddIDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddMajorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddLevelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddAgeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(77, Short.MAX_VALUE))
        );

        studentAddLevelCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD"}));

        javax.swing.GroupLayout studentAddFieldPanelLayout = new javax.swing.GroupLayout(studentAddFieldPanel);
        studentAddFieldPanel.setLayout(studentAddFieldPanelLayout);
        studentAddFieldPanelLayout.setHorizontalGroup(
                studentAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(studentAddIDField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(studentAddNameField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 422, Short.MAX_VALUE)
                        .addComponent(studentAddMajorField, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(studentAddLevelCombo, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentAddAgeField, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        studentAddFieldPanelLayout.setVerticalGroup(
                studentAddFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentAddFieldPanelLayout.createSequentialGroup()
                                .addComponent(studentAddIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddLevelCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        studentAddMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        studentAddMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentAddMainLabel.setText("Add a new student");

        studentAddSubmitButton.setText("Submit");
        studentAddSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddSubmitButtonActionPerformed(evt);
            }
        });

        studentAddClearButton.setText("Clear");
        studentAddClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentAddClearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout studentAddTabLayout = new javax.swing.GroupLayout(studentAddTab);
        studentAddTab.setLayout(studentAddTabLayout);
        studentAddTabLayout.setHorizontalGroup(
                studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentAddTabLayout.createSequentialGroup()
                                .addComponent(studentAddLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(studentAddMainLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentAddTabLayout.createSequentialGroup()
                                .addGap(199, 199, 199)
                                .addComponent(studentAddSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(studentAddClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213))
        );
        studentAddTabLayout.setVerticalGroup(
            studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(studentAddTabLayout.createSequentialGroup()
                .addComponent(studentAddMainLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentAddLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentAddFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(studentAddTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentAddClearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentAddSubmitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        studentTab.addTab("Add", studentAddTab);

        studentUpdateTable.setModel(new javax.swing.table.DefaultTableModel(
                studentDatabase.searchStudent(),
                new String[]{
                        "ID", "Name", "Major", "Level", "Age"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
        });
        studentUpdateTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentUpdateTableMousePressed(evt);
            }
        });
        studentUpdateScrollPanel.setViewportView(studentUpdateTable);
        if (studentUpdateTable.getColumnModel().getColumnCount() > 0) {
            studentUpdateTable.getColumnModel().getColumn(0).setResizable(false);
            studentUpdateTable.getColumnModel().getColumn(1).setResizable(false);
            studentUpdateTable.getColumnModel().getColumn(2).setResizable(false);
            studentUpdateTable.getColumnModel().getColumn(3).setResizable(false);
            studentUpdateTable.getColumnModel().getColumn(4).setResizable(false);
        }

        studentUpdateMainLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        studentUpdateMainLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentUpdateMainLabel.setText("Update a student entry");

        studentUpdateIDLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateIDLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateIDLabel.setText("ID:");

        studentUpdateNameLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateNameLabel.setText("Name:");

        studentUpdateMajorLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateMajorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateMajorLabel.setText("Major:");

        studentUpdateLevelLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateLevelLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateLevelLabel.setText("Level");

        studentUpdateAgeLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        studentUpdateAgeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        studentUpdateAgeLabel.setText("Age");

        javax.swing.GroupLayout studentUpdateLabelPanelLayout = new javax.swing.GroupLayout(studentUpdateLabelPanel);
        studentUpdateLabelPanel.setLayout(studentUpdateLabelPanelLayout);
        studentUpdateLabelPanelLayout.setHorizontalGroup(
                studentUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(studentUpdateIDLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentUpdateNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                        .addComponent(studentUpdateMajorLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentUpdateLevelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(studentUpdateAgeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        studentUpdateLabelPanelLayout.setVerticalGroup(
                studentUpdateLabelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentUpdateLabelPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(studentUpdateIDLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateMajorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateLevelLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateAgeLabel)
                                .addContainerGap(50, Short.MAX_VALUE))
        );

        studentUpdateIDField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateNameField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateMajorField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateAgeField.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N

        studentUpdateLevelSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Freshman", "Sophomore", "Junior", "Senior", "Masters", "PhD"}));

        javax.swing.GroupLayout studentUpdateFieldPanelLayout = new javax.swing.GroupLayout(studentUpdateFieldPanel);
        studentUpdateFieldPanel.setLayout(studentUpdateFieldPanelLayout);
        studentUpdateFieldPanelLayout.setHorizontalGroup(
                studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentUpdateFieldPanelLayout.createSequentialGroup()
                                .addGroup(studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentUpdateIDField)
                                        .addComponent(studentUpdateNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                                        .addComponent(studentUpdateMajorField)
                                        .addComponent(studentUpdateAgeField)
                                        .addComponent(studentUpdateLevelSelect, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        studentUpdateFieldPanelLayout.setVerticalGroup(
                studentUpdateFieldPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(studentUpdateFieldPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(studentUpdateIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateMajorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateLevelSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentUpdateAgeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(44, Short.MAX_VALUE))
        );

        studentUpdateSubmitButton.setText("Submit");
        studentUpdateSubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUpdateSubmitButtonActionPerformed(evt);
            }
        });
        studentUpdateSplitPane.setLeftComponent(studentUpdateSubmitButton);

        studentUpdateClearButton.setText("Clear");
        studentUpdateClearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentUpdateClearButtonActionPerformed(evt);
            }
        });
        studentUpdateSplitPane.setRightComponent(studentUpdateClearButton);

        studentUpdateOldSid.setText("jTextField1");

        javax.swing.GroupLayout studentUpdateTabLayout = new javax.swing.GroupLayout(studentUpdateTab);
        studentUpdateTab.setLayout(studentUpdateTabLayout);
        studentUpdateTabLayout.setHorizontalGroup(
            studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentUpdateScrollPanel)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(studentUpdateLabelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateFieldPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(studentUpdateTabLayout.createSequentialGroup()
                .addGap(336, 336, 336)
                .addComponent(studentUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(studentUpdateOldSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        studentUpdateTabLayout.setVerticalGroup(
            studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, studentUpdateTabLayout.createSequentialGroup()
                .addComponent(studentUpdateMainLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(studentUpdateTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(studentUpdateLabelPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(studentUpdateFieldPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentUpdateSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(studentUpdateOldSid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        studentTab.addTab("Update", studentUpdateTab);

        jTabbedPane1.addTab("Student", studentTab);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null},
                        {null, null, null, null, null}
                },
                new String[]{
                        "ID", "Name", "Major", "Level", "Age"
                }
        ) {
            Class[] types = new Class[]{
                    java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("ID");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Name");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Major");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Level");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Age");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        studentSearchMajorField1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        studentSearchLevelField1.setModel(new javax.swing.DefaultComboBoxModel(new String[]{"Item 1", "Item 2", "Item 3", "Item 4"}));

        studentSearchSubmitButton1.setText("Search");
        studentSearchSubmitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchSubmitButton1ActionPerformed(evt);
            }
        });

        studentSearchClearButton1.setText("Clear");
        studentSearchClearButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentSearchClearButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studentSearchAgeField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(studentSearchLevelField1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentSearchMajorField1, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(studentSearchNameField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(studentSearchIDField1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel6Layout.createSequentialGroup()
                                                .addComponent(studentSearchSubmitButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(studentSearchClearButton1)))
                                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(studentSearchIDField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchNameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchMajorField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchLevelField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(studentSearchAgeField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentSearchSubmitButton1)
                    .addComponent(studentSearchClearButton1))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout staffSearchTabLayout = new javax.swing.GroupLayout(staffSearchTab);
        staffSearchTab.setLayout(staffSearchTabLayout);
        staffSearchTabLayout.setHorizontalGroup(
                staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffSearchTabLayout.createSequentialGroup()
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
        );
        staffSearchTabLayout.setVerticalGroup(
            staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffSearchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(staffSearchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(staffSearchTabLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Search", staffSearchTab);

        jTabbedPane1.addTab("Staff", jTabbedPane3);
        jTabbedPane1.addTab("Faculty", jTabbedPane4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentSearchSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchSubmitButtonActionPerformed
        // TODO add your handling code here:

        String sid = studentSearchIDField.getText();
        int id = -1;
        if (!sid.equals("")) {
            id = Integer.parseInt(sid);
        }
        String name = studentSearchNameField.getText();
        if (name.equals("")) {
            name = null;
        }
        String major = (String) studentSearchMajorField.getSelectedItem();
        if (studentSearchMajorField.getSelectedIndex() == 0) {
            major = null;
        }
        String level = (String) studentSearchLevelField.getSelectedItem();
        if (studentSearchLevelField.getSelectedIndex() == 0) {
            level = null;
        }
        String sAge = studentSearchAgeField.getText();
        int age = -1;
        if (!sAge.equals("")) {
            age = Integer.parseInt(sAge);
        }
        String[] columns = {"ID", "Name", "Major", "Level", "Age"};

        Object[][] newData;
        if (id == -1 && name == null && major == null && level == null && age == -1) {
            newData = studentDatabase.searchStudent();
        } else {
            newData = studentDatabase.searchStudent(id, name, major, level, age);
        }
        refresh(studentSearchTable, columns, newData);

    }//GEN-LAST:event_studentSearchSubmitButtonActionPerformed

    private void studentSearchClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchClearButtonActionPerformed
        // TODO add your handling code here:
        studentSearchIDField.setText("");
        studentSearchNameField.setText("");
        studentSearchMajorField.setSelectedIndex(0);
        studentSearchLevelField.setSelectedIndex(0);
        studentSearchAgeField.setText("");
        // TODO add search with no items
    }//GEN-LAST:event_studentSearchClearButtonActionPerformed

    private void studentAddSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddSubmitButtonActionPerformed
        // TODO add your handling code here:
        int id, age;
        try {
            id = Integer.parseInt(studentAddIDField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You must put in a valid number for ID");
            return;
        }
        String name = studentAddNameField.getText();
        if (name.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a valid name");
            return;
        }
        String major = studentAddMajorField.getText();
        if (major.equals("")) {
            JOptionPane.showMessageDialog(null, "You must enter a valid major");
            return;
        }
        String level = (String) studentAddLevelCombo.getSelectedItem();
        try {
            age = Integer.parseInt(studentAddAgeField.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You must put in a valid number for age");
            return;
        }


        studentDatabase.insertStudent(id, name, major, level, age);
    }//GEN-LAST:event_studentAddSubmitButtonActionPerformed

    private void studentAddClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentAddClearButtonActionPerformed
        // TODO add your handling code here:
        studentAddIDField.setText("");
        studentAddNameField.setText("");
        studentAddMajorField.setText("");
        studentAddLevelCombo.setSelectedIndex(0);
        studentAddAgeField.setText("");
    }//GEN-LAST:event_studentAddClearButtonActionPerformed

    private void studentUpdateSubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUpdateSubmitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentUpdateSubmitButtonActionPerformed

    private void studentUpdateClearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentUpdateClearButtonActionPerformed
        // TODO add your handling code here:
        studentUpdateIDField.setText("");
        studentUpdateNameField.setText("");
        studentUpdateMajorField.setText("");
        studentUpdateLevelSelect.setSelectedIndex(0);
        studentUpdateAgeField.setText("");
    }//GEN-LAST:event_studentUpdateClearButtonActionPerformed

    private void studentSearchSubmitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchSubmitButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentSearchSubmitButton1ActionPerformed

    private void studentSearchClearButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentSearchClearButton1ActionPerformed
        // TODO add your handling code here:
        studentSearchIDField.setText("");
        studentSearchNameField.setText("");
        studentSearchMajorField.setSelectedIndex(0);
        studentSearchLevelField.setSelectedIndex(0);
        studentSearchAgeField.setText("");
    }//GEN-LAST:event_studentSearchClearButton1ActionPerformed

    private void studentUpdateTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentUpdateTableMousePressed
        // TODO add your handling code here:
        JTable target = (JTable) evt.getSource();
        int row = target.getSelectedRow();

        int id = (Integer) target.getValueAt(row, 0);
        String name = (String) target.getValueAt(row, 1);
        String major = (String) target.getValueAt(row, 2);
        String level = (String) target.getValueAt(row, 3);
        int age = (Integer) target.getValueAt(row, 4);

        studentUpdateIDField.setText(id + "");
        studentUpdateNameField.setText(name);
        studentUpdateMajorField.setText(major);

    }//GEN-LAST:event_studentUpdateTableMousePressed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StaffForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StaffForm().setVisible(true);
            }
        });
    }

    protected void getStudenTable(){
        //tableValues = ;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel staffSearchTab;
    private javax.swing.JTextField studentAddAgeField;
    private javax.swing.JLabel studentAddAgeLabel;
    private javax.swing.JButton studentAddClearButton;
    private javax.swing.JPanel studentAddFieldPanel;
    private javax.swing.JTextField studentAddIDField;
    private javax.swing.JLabel studentAddIDLabel;
    private javax.swing.JPanel studentAddLabelPanel;
    private javax.swing.JComboBox studentAddLevelCombo;
    private javax.swing.JLabel studentAddLevelLabel;
    private javax.swing.JLabel studentAddMainLabel;
    private javax.swing.JTextField studentAddMajorField;
    private javax.swing.JLabel studentAddMajorLabel;
    private javax.swing.JTextField studentAddNameField;
    private javax.swing.JLabel studentAddNameLabel;
    private javax.swing.JButton studentAddSubmitButton;
    private javax.swing.JPanel studentAddTab;
    private javax.swing.JTextField studentSearchAgeField;
    private javax.swing.JTextField studentSearchAgeField1;
    private javax.swing.JButton studentSearchClearButton;
    private javax.swing.JButton studentSearchClearButton1;
    private javax.swing.JTextField studentSearchIDField;
    private javax.swing.JTextField studentSearchIDField1;
    private javax.swing.JComboBox studentSearchLevelField;
    private javax.swing.JComboBox studentSearchLevelField1;
    private javax.swing.JComboBox studentSearchMajorField;
    private javax.swing.JComboBox studentSearchMajorField1;
    private javax.swing.JTextField studentSearchNameField;
    private javax.swing.JTextField studentSearchNameField1;
    private javax.swing.JButton studentSearchSubmitButton;
    private javax.swing.JButton studentSearchSubmitButton1;
    private javax.swing.JPanel studentSearchTab;
    private javax.swing.JTable studentSearchTable;
    private javax.swing.JTabbedPane studentTab;
    private javax.swing.JTextField studentUpdateAgeField;
    private javax.swing.JLabel studentUpdateAgeLabel;
    private javax.swing.JButton studentUpdateClearButton;
    private javax.swing.JPanel studentUpdateFieldPanel;
    private javax.swing.JTextField studentUpdateIDField;
    private javax.swing.JLabel studentUpdateIDLabel;
    private javax.swing.JPanel studentUpdateLabelPanel;
    private javax.swing.JLabel studentUpdateLevelLabel;
    private javax.swing.JComboBox studentUpdateLevelSelect;
    private javax.swing.JLabel studentUpdateMainLabel;
    private javax.swing.JTextField studentUpdateMajorField;
    private javax.swing.JLabel studentUpdateMajorLabel;
    private javax.swing.JTextField studentUpdateNameField;
    private javax.swing.JLabel studentUpdateNameLabel;
    private javax.swing.JTextField studentUpdateOldSid;
    private javax.swing.JScrollPane studentUpdateScrollPanel;
    private javax.swing.JSplitPane studentUpdateSplitPane;
    private javax.swing.JButton studentUpdateSubmitButton;
    private javax.swing.JPanel studentUpdateTab;
    private javax.swing.JTable studentUpdateTable;
    // End of variables declaration//GEN-END:variables
    private Object[][] tableValues;
    private StudentDatabase studentDatabase;
    private FacultyDatabase facultyDatabase;
    private StaffDatabase staffDatabase;
    private GeneralDatabase generalDatabase;
}
